version: '2.3'

services:
  proxy:
    image: nginx:1.11.10-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    image: node:10.9.0-alpine
    working_dir: /service
    volumes:
      - ./:/service
    ports:
      - 3000:3000
      - 9000:9000
    command: ['npm', 'run', 'start']

networks:
  default:
    external:
      name: local
